theme: jekyll-theme-minimal
logo: img/starlightstudio.png
title: Starlight Studio
description: A program of the Groff Family Foundation, a 501(c)(3) corporation dedicated to community-focused high-impact charitable work.
